name: Custom
url: https://madtinker.net
description: The Mad Tinker

permalink: /:categories/:year/:month/:day/:title/
paginate: 1

plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
baseurl: /

